### ISSUE TITLE
Why Markdown when they are HTML (i think)

### ISSUE THREAD

**Issue by Danix421** [Ileriayo/markdown-badges#67] opened 2021-03-12 22:59 UTC
Hi, i'm Danix, a developer. I viewed this repo by the GitHub recomendations but when i opened it, viewed an error: his name is "markdown-badges" and say that there are markdown badge but they aren't markdown, they are html (i think)! This is not an urgency but i think it is bad. I hope this repo creator fix it.

**Comment by 727021** [comment] 2021-04-20 19:47
Duplicate of #49

**Closed** 2021-04-20 20:22 UTC
